const obj = {
  name: "Android Developer",
  email: "info@qwikresume.com",
  mobile_number: None,
  skills: [
    "C",
    "Android",
    "Python",
    "Publishing",
    "Java",
    "Specifications",
    "Xml",
    "Website",
    "Debugging",
    "Mobile",
    "Json",
    "Analysis",
    "Ui",
    "Cloud",
    "Matlab",
    "Testing",
    "Design",
    "Construction",
    "Javascript",
    "Email",
  ],
  college_name: None,
  degree: None,
  designation: None,
  experience: [
    "Android Developer",
    "ABC Corporation\xa0\xad\xa0January 2011 – March 2012",
    "\uf09f Environment Eclipse IDE, Android Studio, GenyMotion, Java, Android SDK, Android",
    "\uf09f",
    "Development Tools (ADT), JSON, XML,",
    "Involved in the full life cycle of the project including analysis design, development, debugging,",
    "testing, and deployment.",
    "\uf09f Developed the application from specifications and requirement gathering.",
    "\uf09f",
    "Independently handled modules, scope, analysis, design, build, test the code, debug and",
    "implement application.",
    "\uf09f Developed products section of the application which provided Multiple Activities, Custom",
    "Adapters, Base Adapter, List views, Links, Web View, Text Views and so on.",
    "\uf09f Developed Navigation Drawer for the application, which provides better navigation of apps",
    "features.",
    "\uf09f Created new UI Screens and key resource for layout UI work utilizing xml, Shape Drawable,",
    "Text View, List View, Web View, Buttons, Activities, and Frame Layout.",
    "Android Developer",
    "ABC Corporation\xa0\xad\xa02006 – 2011",
    "\uf09f Helped Develop Insight, which is a tablet application that retrieves data from a CPE and",
    "displays it",
    "\uf09f This is done to debug the DSL activity in someones home",
    "\uf09f Pulled info from a cloud server and coded it onto a tablet",
    "\uf09f Worked on UI and backend construction",
    "\uf09f Connected to various computer boards where I retrieved Wi-Fi information from a server -",
    "Debugged code that was previously worked on by an outsourced company",
    "\uf09f There were many bugs and crashes in the app, and I cleaned them all, despite the size of the",
    "code",
    "\uf09f Retrieved wiring and noise data from the CPE by connecting the tablet to the same network.",
    "© This Free Resume Template is the copyright of Qwikresume.com. Usage",
    "Guidelines",
  ],
  company_names: ["ROBERT SMITH"],
  no_of_pages: 2,
  total_experience: 1.17,
};

const dataScientist = {
  name: "Data Scientist",
  email: "info@qwikresume.com",
  mobile_number: None,
  skills: [
    "Analytical",
    "Algorithms",
    "Website",
    "Conversion",
    "Scala",
    "Machine learning",
    "Programming",
    "Analysis",
    "Litigation",
    "Email",
    "Documentation",
    "Data analysis",
    "Python",
    "Sphinx",
    "Mining",
    "Matlab",
    "Reporting",
    "Analytics",
    "Design",
    "Process",
    "R",
    "Research",
    "Spark",
    "Automation",
    "Cloud",
    "Aws",
    "Etl",
    "Physics",
  ],
  college_name: None,
  degree: None,
  designation: None,
  experience: [
    "Data Scientist",
    "ABC Corporation\xa0\xad\xa0May 1994 – May 2005",
    "\uf09f Assisted in determining client needs, deliverable design, estimates and feasibility for",
  ],
  company_names: None,
  no_of_pages: 2,
  total_experience: 11.0,
};
